### ISSUE TITLE
Spectrum Similarity with return possibility for plot and alignment dataframe

### ISSUE THREAD

**Issue by michaelwitting** [OrgMassSpec/OrgMassSpecR#1]
Hello,

might it be possible to also get the plot and alignment dataframe from the function?
Maybe as return a list() containing all three?

Best regards,

Michael

PS: I can do a branch if you like

**Comment by OrgMassSpec** [comment]
Hi Michael,

Please see the linked R script below (.txt file) and let me know if this works.

[SimilarityScoreModified.txt](https://github.com/OrgMassSpec/OrgMassSpecR/files/626249/SimilarityScoreModified.txt)

The plot returned in the list is generated by grid graphics in order to save it as an object. I also had to be careful about backwards compatibility. 

Before incorporating this into the package, I will probably make a method for the print generic so that the user can view the plot using print(x$plot), similar to ggplot2 and lattice.

Best,
Nate

**Comment by OrgMassSpec** [comment]
Change made in version 0.5-1. (Source package available in the GitHub repository.)
